name: Release
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-18-18-node-modules-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-18-18-node-modules-

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: dotansimha/changesets-action@262e957f99be29087d2b13afa32a5d579bf1d080
        with:
          publish: 'yarn release'
          commit: 'chore(release): update monorepo packages versions'
          title: 'Upcoming Release Changes'
          createGithubReleases: aggregate
          githubReleaseName: "Release ${{ steps.vars.outputs.sha_short }} (from ${{ steps.vars.outputs.branch }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}