name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: yarn ci:lint
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: typecheck / graphql v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15, 16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.mjs ${{matrix.graphql_version}}

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: packages/plugin/dist

  test:
    name: jest / node v${{matrix.node_version}} / graphql v${{matrix.graphql_version}} / eslint v8
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [typecheck]
    strategy:
      matrix:
        node_version: [12, 16, 18]
        graphql_version: [15, 16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{matrix.node-version}}

      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node scripts/match-graphql.mjs ${{matrix.graphql_version}}

      - name: Install Dependencies
        run: yarn

      - name: Cache Jest
        uses: actions/cache@v3
        with:
          path: .cache/jest
          key: ${{runner.os}}-${{matrix.node_version}}-jest-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-${{matrix.node_version}}-jest-

      # We need build for examples.spec.ts test
      # Otherwise we'll get error - Cannot find module 'node_modules/@graphql-eslint/eslint-plugin/dist/index.js'
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: packages/plugin/dist

      - name: Test
        run: yarn test
        env:
          CI: true
