name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: pnpm ci:lint
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: typecheck / graphql v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15, 16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ENV
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node scripts/match-graphql.js ${{matrix.graphql_version}}

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: packages/plugin/dist

  test:
    name: Node.js v${{matrix.node_version}} / GraphQL v${{matrix.graphql_version}} / ESLint v8
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [typecheck]
    strategy:
      matrix:
        node_version: [16, 18, 20]
        graphql_version: [15, 16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ENV
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{matrix.node_version}}
          packageManager: pnpm

      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node scripts/match-graphql.js ${{matrix.graphql_version}}

      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile

      # We need build for examples.spec.ts test
      # Otherwise we'll get error - Cannot find module 'node_modules/@graphql-eslint/eslint-plugin/dist/index.js'
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: packages/plugin/dist

      - name: Test
        run: pnpm test
        env:
          CI: true
#      - name: Lint ESLint
#        run: pnpm lint
#
#      - name: Lint Prettier
#        run: pnpm lint:prettier
