name: Website Integrity
on:
  pull_request:
    paths:
      - 'website/**'
jobs:
  website-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch
        run: git fetch origin master

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18

      - name: Build Packages
        run: pnpm build

      - name: Build Website
        run: pnpm --filter website build

      - name: Compare
        run: git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt

      - name: Diff to file
        if: always()
        id: diff_result
        run: |
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(git diff origin/${{ github.base_ref }}.. -- website/route-lockfile.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Publish a message
        if: always() && contains(steps.diff_result.outputs.result, 'diff')
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ```diff
            ${{ steps.diff_result.outputs.result }}
            ```
